name: Build

on:
  - push
  - pull_request

jobs:

  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 14

      - run: |
          chmod +x ./gradlew
          ./gradlew test


  check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 14

      - run: |
          chmod +x ./gradlew
          ./gradlew detekt

      - uses: github/codeql-action/upload-sarif@v1
        if: always()
        with:
          sarif_file: build/reports/detekt
